name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      # local build
      - name: Compile the binary
        run: |
          make bin/goldpinger
          ./bin/goldpinger -h

      # simple Docker build
      - name: Build the Docker image
        run: |
          make build
          docker run `make version` --help

      # multi-arch build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build regular image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          target: simple
      - name: Build vendor image
        id: docker_build_vendor
        uses: docker/build-push-action@v6
        with:
          context: .
          flavor: |
            suffix: -vendor,onlatest=false
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          target: vendor
